version: "3.8"

services:
  db_cont: 
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: notesdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  django_app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db_cont
    environment:
      DB_HOST: db_cont
      DB_NAME: notesdb
      DB_USER: root
      DB_PASSWORD: root

volumes:
  db_data:
